FROM apache/airflow:2.10.4-python3.12

RUN pip install apache-airflow-providers-apache-spark
RUN pip install --upgrade google-cloud-bigquery

USER root
RUN apt-get update \
    && apt-get install -y openjdk-17-jre-headless \
    && apt-get clean

ENV JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
ENV PATH=$JAVA_HOME/bin:$PATH

USER airflow
